server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Isso é crucial para aplicações React (Single Page Applications)
        # Se a rota não for um arquivo físico, redireciona para o index.html
        try_files $uri $uri/ /index.html;
    }
}
